### DISCUSSION TITLE
Problems backing up public and private repos and issues with PAT

### DISCUSSION THREAD

**Discussion by nidomiro** [cooperspencer/gickup#236] [Q&A]
My current PAT has the following permissions:
```
read:audit_log,
read:discussion,
read:enterprise,
read:gpg_key,
read:org,
read:packages,
read:project,
read:public_key,
read:repo_hook,
read:ssh_signing_key,
read:user,
repo,
user:email
```
During backing up I get errors like:

```
2024-04-26T19:53:53Z INF starting backup for https://github.com/nidomiro/ts-tools.git stage=backup
2024-04-26T19:53:53Z INF cloning github.com/nidomiro/ts-tools.git/1714161233 path=/backup-data/ stage=locally
2024-04-26T19:53:54Z INF backing up issues path=/backup-data/ repo=github.com/nidomiro/ts-tools.git/1714161233 stage=locally
2024-04-26T19:53:54Z ERR open /backup-data/github.com/nidomiro/ts-tools.git/1714161233.issues/48.json: no such file or directory path=/backup-data/ stage=locally

```

This error also happens for private repos.
What is strage to me is the `1714161233` in the repo and issue URL.
Also the git folder inside the zip-file seems wrong, inside `objects/` there are only two files under `objects/pack` and `branches/` is totally empty.

The config I used:
```yaml
source:
  github:
    - token: myToken
    # alternatively, specify token in a file, relative to current working directory when executed.
      # token_file: token.txt
      #user: nidomiro # the user you want to clone the repositories from.
      # if you want to get everything from your user, leave out the user parameter and just use the token.
      # for the clone process, either use:
      # - username + password
      # - sshkey
      # - token
#      username: nidomiro # user is used to clone the repo with
#      password: your-password
#      ssh: true # can be true or false
#      sshkey: /path/to/key # if empty, it uses your home directories' .ssh/id_rsa
#      exclude: # this excludes the repos "foo" and "bar"
#        - foo
#        - bar
#      include: # this includes the repo "foobar"
#        - cooperspencer/gickup
#        - hashicorp/nomad
#      excludeorgs: # this excludes repos from the organizations "foo" and "bar"
#        - foo
#        - bar
#      includeorgs: # this includes repos from the organizations "foo1" and "bar1"
#        - foo1
#        - bar1
      wiki: true # includes wiki too
      issues: true # back up issues, works only locally
      starred: false # includes the user's starred repositories too
      filter:
#        stars: 100 # only clone repos with 100 stars
#        lastactivity: 1y # only clone repos which had activity during the last year
#        excludearchived: true
#        languages: # only clone repositories with the following languages
#          - go
#          - java
        excludeforks: true # exclude forked repositories

destination:
  local:
    # Export this path from Docker with a volume to make it accessible and more permanent.
    - path: /backup-data/
      structured: true # checks repos out like hostersite/user|organization/repo
      zip: true # zips the repository after cloned and removes the repository afterwards
      keep: 5 # only keeps x backups
      bare: true # clone the repositories as bare
      lfs: true # clone lfs repos, !! ATTENTION !! git and git-lfs must be installed on the system!

log:
  file-logging: # optional
    dir: /backup-data/ # directory to log into
    file: gickup.log # file to log into
    maxage: 7 # keep logs for 7 days
```
I'm using the docker image: `buddyspencer/gickup:ubuntu-latest` with the ImageID `3d9a76d5d0ea`

How can I fix this and get backups of these issues?
