### DISCUSSION TITLE
Github Token

### DISCUSSION THREAD

**Discussion by gerardo-cipriano-dinova** [cooperspencer/gickup#247] [Q&A] [answered]
I'm having trouble with my GitHub token. I created a new one with full access, but I keep getting a "bad credentials" error when I try to use it in gickup.

I can authenticate just fine using curl from my shell, so it seems like the issue is with the token itself or how it's being used with the action.

I've tried generating new tokens with different scopes and checked the documentation, but nothing seems to work.

Here's my workflow config for reference:

```
source:
  github:
    - token: ghp_oPAxxxxxxxxxxxxxx3NFyoOeS0V9p0N
      includeorgs:
        - myorg
      ssh: false
      exclude:
      include:
      excludeorgs:
      wiki: true
      starred: true
      issues: true
destination:
  local:
    - path: /gickup/backup
      structured: true
      zip: true
      keep: 180
      bare: true
      lfs: false
```

Any suggestions on what I might be missing?

Thanks,
