### DISCUSSION TITLE
Need a little help with bitbucket: 429 and 404 errors

### DISCUSSION THREAD

**Discussion by andrew-dotlovesdata** [cooperspencer/gickup#293] [Q&A]
I'm trying to back up some repos in my companies bitbucket. At the moment its only a couple of repos in a project for testing purposes.
I'm currently getting this log output:

> 2025-02-05 13:15:00 INF Backup run starting
> 2025-02-05 13:15:00 INF grabbing repositories from  stage=bitbucket url=https://api.bitbucket.org/2.0
> 2025-02-05 13:29:50 ERR 429 Too Many Requests stage=bitbucket url=https://api.bitbucket.org/2.0
> 2025-02-05 13:29:50 INF grabbing repositories from  stage=bitbucket url=https://bitbucket.org
> 2025-02-05 13:29:51 ERR 404 Not Found stage=bitbucket url=https://bitbucket.org
> 2025-02-05 13:29:51 INF Backup run complete duration=14m51.604473503s

This is the source in my conf.yml:

> source:
>   bitbucket:
>     - user:  # the user you want to clone the repositories from.
>     - token: REDACTED
>       # token_file: token.txt # alternatively, specify token in a file
>       url: https://bitbucket.org # if empty, it uses https://bitbucket.org
>       # username: andrew # user is used to clone the repo with
>       #password: 
>       ssh: true # can be true or false
>       sshkey: ~/.ssh/id_ed25519 # if empty, it uses your home directories' .ssh/id_rsa
>       #exclude: # this excludes the repos foo and bar
>       include: # this includes the repo "foobar"
>         - deployment
>       #excludeorgs: # this excludes repos from the workpaces "foo" and "bar"
>       includeorgs: # this includes repos from the workspaces "foo1" and "bar1"
>         # - "Company Name"
>       filter:
>         lastactivity: 1y # only clone repos which had activity during the last year

        
I'm not sure what I'm doing wrong here.
I did have the username populated originally, but after re-reading the docs i noted that I didn't need it (it was giving me a 401 error as well)
Also, is the URL correct? or does it need to include my org name as well, like: https://bitbucket.org/companyname

Edit:
I tried with the url above and got the same error:

> 2025-02-05 14:30:00 INF Backup run starting
> 2025-02-05 14:30:00 INF grabbing repositories from  stage=bitbucket url=https://api.bitbucket.org/2.0
> 2025-02-05 14:45:06 ERR 429 Too Many Requests stage=bitbucket url=https://api.bitbucket.org/2.0
> 2025-02-05 14:45:06 INF grabbing repositories from  stage=bitbucket url=https://bitbucket.org/companyname
> 2025-02-05 14:45:07 ERR 404 Not Found stage=bitbucket url=https://bitbucket.org/companyname
> 2025-02-05 14:45:07 INF Backup run complete duration=15m7.034137581s

**Comment by cooperspencer** [comment]
Hi there,

I'll have a look and get back to you.

**Reply by cooperspencer** [reply]
I created an app password in the "Personal Bitbucket Settings" and can clone my own repos with that. 
I used the following configuration to clone my repos and workspace:
```yaml
source:
  bitbucket:
    - token: REDACTED
      user: buddyspencer
destination:
  local:
    - path: ~/backup
      structured: true
```

**Reply by cooperspencer** [reply]
A friend of mine helped me out here. Can you try the following:
```yaml
source:
  bitbucket:
    - token: REDACTED
      username: YOUR-USER
      user: YOUR-COMPANIES-WORKSPACE
destination:
  local:
    - path: ~/backup
      structured: true
```

The workspace can be found if you open a repo there and it should be the first part of the URL after bitbucket.org, so like bitbucket.org/_**whatever**_/bla/src/main

**Reply by andrew-dotlovesdata** [reply]
Thanks for the response Cooper.
I have followed your suggestion:
```
source:
  bitbucket:
    - user:  company-workspace
    - token: REDACTED
      # token_file: token.txt # alternatively, specify token in a file
      url: https://bitbucket.org # if empty, it uses https://bitbucket.org
      username: andrew@company.com # user is used to clone the repo with
      # password: 
      ssh: true # can be true or false
      sshkey: ~/.ssh/id_ed25519 # if empty, it uses your home directories' .ssh/id_rsa
      #exclude: # this excludes the repos foo and bar
      include: # this includes the repo "foobar"
        - deployment
      #excludeorgs: # this excludes repos from the workpaces "foo" and "bar"
      #includeorgs: # this includes repos from the workspaces "foo1" and "bar1"
       filter:
        lastactivity: 1y # only clone repos which had activity during the last year
```
I'm not getting the 429 too many requests error now, so there's progress, but now the 404 error is a 401 Unauthorized error:
```
2025-02-07 09:38:49 INF Backup run starting
2025-02-07 09:38:49 INF grabbing repositories from dotlovesdata stage=bitbucket url=https://api.bitbucket.org/2.0
2025-02-07 09:38:50 INF grabbing repositories from andrew@dotlovesdata.com stage=bitbucket url=https://bitbucket.org
2025-02-07 09:38:50 ERR 401 Unauthorized stage=bitbucket url=https://bitbucket.org
2025-02-07 09:38:50 INF Backup run complete duration=1.403749142s
```
I've tried with various combo's of ssh key, password, username - i get the 404 error when i remove the username.
I also created a new id_rsa ssh key and added it as a workspace key, but still getting the 401 error. I also changed the token to a workspace token (instead of a personal one) but same issue.
