### DISCUSSION TITLE
Question about cloning Github repos under different accounts

### DISCUSSION THREAD

**Discussion by Aetherinox** [cooperspencer/gickup#329] [Q&A]
I was wondering if it's possible to clone repositories from Github that are owned by different accounts (that I have access to) and have them published under Gitea as that user.

As an example, I have my Github personal account, but I also have an organization.

I want gickup to clone my personal github repos, and post them under my Gitea website under my account. But then clone all of the organization repos and have them posted in Gitea under an organization profile. And then also include other users (see example below)

I tried the following config, I Just grabbed two random Github repos, yours and authentik

```yml
source:
  github:
    - user: cooperspencer
      token: XXXX
      include:
        - gickup
      wiki: true
      issues: true

    - user: goauthentik
      token: XXXX
      include:
        - authentik
      wiki: true
      issues: true

destination:
  gitea:
    - user: cooperspencer
      token: XXXX
      url: http://gitea:3000/
      createorg: true
      lfs: false
      visibility:
        repositories: public
        organizations: public
      mirror:
        enabled: true
        mirrorinterval: 2h0m0

    - user: goauthentik
      token: XXXX
      url: http://gitea:3000/
      createorg: true
      lfs: false
      visibility:
        repositories: public
        organizations: public
      mirror:
        enabled: true
        mirrorinterval: 2h0m0
```

<br />

Maybe I'm misunderstanding how it works. But it does create two new orgs, but then you end up with the following repos:

- cooperspencer/authentik
- goauthentik/authentik

- cooperspencer/gickup
- goauthentik/gickup

So it's cloning the first repo twice for two different users.

---

Running via docker-compose.yml

The other issue I notices is that if I attempt to pull a repo which may have a lot of issues, I get the error:

```
WRN can't fetch issues error="GET https://api.github.com/repos/goauthentik/authentik/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=authentik stage=github url=https://github.com

WRN can't fetch issues error="GET https://api.github.com/repos/goauthentik/authentik/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=authentik stage=github url=https://github.com
```

**Comment by Aetherinox** [comment]
So I read through a bunch of issues submitted by users, and I found out about the multiple pair structure for the conf.yml

```yml
source:
  github:
    - user: cooperspencer
      token_file: /gickup/tokens/github.txt
      include:
        - gickup
destination:
  gitea:
    - user: cooperspencer
      token_file: /gickup/tokens/gitea.txt
      url: http://gitea:3000/
      lfs: false
      visibility:
        repositories: public
        organizations: public
---

source:
  github:
    - user: thomiceli
      token_file: /gickup/tokens/github.txt
      include:
        - opengist
destination:
  gitea:
    - user: thomiceli
      token_file: /gickup/tokens/gitea.txt
      url: http://gitea:3000/
      lfs: false
      visibility:
        repositories: public
        organizations: public
```

<br />

If I go into the console to check the test, it appears to work fine. However, now the docker container dies after the operation is complete.

![VziGmikVZE](https://github.com/user-attachments/assets/208a1449-ee47-4e65-a5ee-5ac2451a2cf8)

<br />

```
INF Reading /gickup/conf.yml file=/gickup/conf.yml
INF Configuration loaded destinations=1 pairs=1 sources=1
INF Backup run starting
INF grabbing the repositories from cooperspencer stage=github url=https://github.com
INF Read token file bytes=93 path=/gickup/tokens/github.txt
INF starting backup for https://github.com/cooperspencer/gickup.git stage=backup
INF mirroring gickup to http://gitea:3000/ stage=gitea url=http://gitea:3000/
INF Read token file bytes=40 path=/gickup/tokens/gitea.txt
INF mirrored gickup to http://gitea:3000/ stage=gitea url=http://gitea:3000/
INF Backup run complete duration=2.5079174s
INF Configuration loaded destinations=1 pairs=1 sources=1
INF Backup run starting
INF grabbing the repositories from thomiceli stage=github url=https://github.com
INF Read token file bytes=93 path=/gickup/tokens/github.txt
INF starting backup for https://github.com/thomiceli/opengist.git stage=backup
INF mirroring opengist to http://gitea:3000/ stage=gitea url=http://gitea:3000/
INF Read token file bytes=40 path=/gickup/tokens/gitea.txt
INF mirror of opengist already exists, syncing instead stage=gitea url=http://gitea:3000/
INF successfully synced opengist. stage=gitea url=http://gitea:3000/
INF Backup run complete duration=722.048753ms
INF Next cron run cron="*/5 * * * *" next="2025-05-27 10:55:00"
```

<br />

If I remove the `---` and 2nd entry, the container stays up fine. If I add the `---` and second entry, the task runs immediately after the container is brought up, and then dies.
