### ISSUE TITLE
Can't backup user and orgs

### ISSUE THREAD

**Issue by alec-hs** [cooperspencer/gickup#107]
Config file is below - if I remove the 'user' line in the config then all the repos in my orgs get cloned but when I add the 'user' line back in then nothing gets clone. Any ideas?

```yaml
source:
  github:
    - token_file: token.txt
      username: alec-hs 
      ssh: false
      user: alec-hs
      includeorgs:
        - kestrel-studios
        - seraph-ai
        - stratos-sh
      wiki: true 
      starred: true 
destination:
  local:
    - path: /backups/
      structured: true 
```

**Comment by cooperspencer** [comment]
Good question. I just tried to reproduce it, but it works for me anyway.

**Comment by colindean** [comment]
@alec-hs Can you provide your full transcript? Post it in a comment or in a [gist](https://gist.github.com) if it's really long.

Pure speculation: 

1. Not specifying it causes this line to error: https://github.com/cooperspencer/gickup/blob/646b792ac13f6aacf04e8c0ef372a6ade9125d2a/github/github.go#L37
2. Not specifying it causes this check to error: https://github.com/cooperspencer/gickup/blob/646b792ac13f6aacf04e8c0ef372a6ade9125d2a/github/github.go#L70-L72

**Comment by alec-hs** [comment]
Ok so I think I've worked part of it out - it was due to me have both `username` and `token_file` in the config. When I removed the `username` it correctly started cloning all my own repos. 

However now it won't clone the included orgs :(

``` yaml
source:
  github:
    - token_file: token.txt
      ssh: false
      user: alec-hs
      includeorgs:
        - kestrel-studios
        - seraph-ai
        - stratos-sh
        - stormworks-cc
      wiki: true 
      starred: true 
destination:
  local:
    - path: /backups/
      structured: true 

cron: '*/5 * * * *' 

log: # optional
  timeformat: 2006-08-22 15:04:05
  file-logging: # optional
    dir: /gickup # directory to log into
    file: gickup.log # file to log into
    maxage: 7 # keep logs for 7 days
```
