### ISSUE TITLE
Ability to include/exclude on destination or have more than one source/destination pair

### ISSUE THREAD

**Issue by thehedgefrog** [cooperspencer/gickup#113]
I use Gickup to make a local backup of a lot of repos, including everything I have starred.  I would like to copy some of those to my local Gitea, but there isn't a need for me to copy all of them to Gitea for various reasons, one of which being disk space usage.

I would like there to be an option to accomodate this workflow rather than running multiple instances of Gickup, I thought of two approaches:

- Make the same include/exclude options on `source` available on `destination` ;
- Allow for more than one `source`/`destination` pair in the config file.

I feel like both of those could bring significant improvements to Gickup, but I think the second one could bring more flexibility.

**Comment by cooperspencer** [comment]
Could you give an example for each option?

**Comment by thehedgefrog** [comment]
Of course.

Make the same include/exclude options on `source` available on `destination`:

```yaml
source: 
  github:
    - token: some-token
      username: thehedgefrog
      wiki: true
      starred: true

destination:
  local:
    - path: /backups/gickup
      structured: true
  gitea:
    - token: some-token
      url: https://gitea.mydomain.com
      includeorgs:
        - thehedgefrog
```

Allow for more than one source/destination pair in the config file:
```yaml
source: 
  github:
    - token: some-token
      username: thehedgefrog
      wiki: true
      starred: true

destination:
  local:
    - path: /backups/gickup
      structured: true

source2:
  github:
    - token: some-token
      username: thehedgefrog
      wiki: true
      includeorgs:
        - thehedgefrog

destination2:
  gitea:
    - token: some-token
      url: https://gitea.mydomain.com
```

**Comment by cooperspencer** [comment]
That might introduce some breaking changes to configuration file. It is possible to define more than one yaml structure in the same file:
```yaml
source: 
  github:
    - token: some-token
      username: thehedgefrog
      wiki: true
      starred: true

destination:
  local:
    - path: /backups/gickup
      structured: true
---
source:
  github:
    - token: some-token
      username: thehedgefrog
      wiki: true
      includeorgs:
        - thehedgefrog

destination:
  gitea:
    - token: some-token
      url: https://gitea.mydomain.com
```
And I could implement to load more than one config file.
