### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vxrtns** [cooperspencer/gickup#117]
Getting this when running the latest version of the Docker container:

```
[+] Running 1/0
 ⠿ Container deleteme-gickup-runner-1  Created                             0.0s
Attaching to deleteme-gickup-runner-1
deleteme-gickup-runner-1  | 2022-10-17T23:02:06+02:00 INF Reading /gickup/conf.yml file=/gickup/conf.yml
deleteme-gickup-runner-1  | 2022-10-17 23:02:06 INF Configuration loaded destinations=1 pairs=1 sources=1
deleteme-gickup-runner-1  | 2022-10-17 23:02:06 INF Backup run starting
deleteme-gickup-runner-1  | 2022-10-17 23:02:06 INF grabbing repositories from my-user stage=gitlab url=my-domain
deleteme-gickup-runner-1  | 2022-10-17 23:02:08 INF Backup run complete duration=1.406142554s
deleteme-gickup-runner-1  | panic: runtime error: invalid memory address or nil pointer dereference
deleteme-gickup-runner-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa4530e]
deleteme-gickup-runner-1  | 
deleteme-gickup-runner-1  | goroutine 1 [running]:
deleteme-gickup-runner-1  | main.main()
deleteme-gickup-runner-1  | 	/go/src/github.com/cooperspencer/gickup/main.go:303 +0x6ce
deleteme-gickup-runner-1 exited with code 2
```

cat docker-compose.yml:
```
version: "3"
services:
  runner:
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/backups:/backups/gitlab
      - ${PWD}/conf.yml:/gickup/conf.yml
    command: ["/gickup/conf.yml"]
    environment:
      - TZ=my-timezone  # redacted
```

cat conf.yml:
```
source:
  gitlab:
    - token: my-token
      user: my-user
      url: my-domain
      #exclude:
      #include:
      wiki: true
destination:
  local:
    - path: /backups/gitlab
      structured: true

#cron: 0 22 * * *

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

metrics:

---
```

I'm trying to back up repos locally from the GitLab CE that my university is hosting (openly accessible).
