### ISSUE TITLE
Add 'excludes' list? (Repositories to skip)

### ISSUE THREAD

**Issue by geerlingguy** [cooperspencer/gickup#14]
I have a few forks of repos that are quite large and I don't really need to backup/mirror them... it would be nice if I could exclude them from gickup somehow, but it looks like there's no way to do that unless I'm missing something?

**Comment by cooperspencer** [comment]
you can get the latest (and greatest) binaries from the actions:
https://github.com/cooperspencer/gickup/actions/runs/1531796153

I just implemented the exclude list and it works like this:
```yaml
source:
  github:
    - user: cooperspencer
      exclude:
        - gickup
        - uas
```
I will also update the documentation for that.
