### ISSUE TITLE
How do I also clone private repositories?

### ISSUE THREAD

**Issue by geerlingguy** [cooperspencer/gickup#16]
I have my config file set up like so:

```
source:
  github:
    - token: [redacted]
      user: geerlingguy
      username: geerlingguy
      ssh: true
      sshkey: /home/pi/.ssh/id_ed25519
      exclude:
        - linux
destination:
  local:
    - path: "/Volumes/Git-Backups"
```

I wasn't quite sure which keys would be required to be able to read private repositories—and I created an app token with read permissions, but not sure which permissions would be required for seeing private repos in the listing, or cloning them (I guess the ssh key would be all that's required for the cloning...).

Is it something I'd have to somehow accomplish separately?
