### ISSUE TITLE
Strange folder creation issue

### ISSUE THREAD

**Issue by kenlasko** [cooperspencer/gickup#186]
I'm taking advantage of multiple source/destination pairs in a single config file. It works very well for backing up my Github repos to a local destination, except for one strange issue.  The second backup path is appended to the first backup path.  Example:

First Destination Path: backup/bare
Second Destination Path: backup/full

The first backup goes to "backup/bare"
The second backup goes to "backup/bare/backup/full"

If I specify the full path, it works fine. So, it's a pretty minor bug, but one that might cause some grief to someone someday.

Conf.yml
```
    source:
      github:
        - token_file: /gickup/tokens/github-token

    destination:
      local:
      - path: backup/bare
        structured: true
        zip: true
        keep: 7
        bare: true

    ---
    source:
      github:
        - token_file: /gickup/tokens/github-token

    destination:
      local:
      - path: backup/full
        structured: true
        zip: true
        keep: 7
        bare: false
```
