### ISSUE TITLE
Not able to mirror gitlab to github

### ISSUE THREAD

**Issue by defyjoy** [cooperspencer/gickup#200]
I have tried whatever combination 
- Given all permissions to token 
- Used `username` + `token`
- Used token file 

I keep getting error as below . What am I doing wrong 
```
myapp-gickup-runner-1  | 2024-01-24T09:11:59+05:30 INF Reading /gickup/conf.yml file=/gickup/conf.yml
myapp-gickup-runner-1  | 2024-01-24 09:11:59 INF Configuration loaded destinations=1 pairs=1 sources=1
myapp-gickup-runner-1  | 2024-01-24 09:11:59 INF Backup run starting
myapp-gickup-runner-1  | 2024-01-24 09:11:59 INF grabbing repositories from  stage=gitlab url=
myapp-gickup-runner-1  | 2024-01-24 09:12:05 INF starting backup for https://gitlab.com/myapp/myapp.git stage=backup
myapp-gickup-runner-1  | 2024-01-24 09:12:05 INF mirroring myapp to https://github.com stage=github url=https://github.com
myapp-gickup-runner-1  | 2024-01-24 09:12:48 ERR authentication required stage=tempclone url=https://gitlab.com/myapp/myapp.git
myapp-gickup-runner-1  | 2024-01-24 09:12:52 INF Backup run complete duration=53.866037817s
```

Here is my configuration

```
source:
  gitlab:
    # - token_file: /gickup/gitlab-token.txt
    # - token_file: gitlab-token.txt
    - ssh: false # can be true or false
      # username: myemail@gmail.com
      token: glpat-abczyx
      includeorgs: 
        - myapp
      include: # this includes the repo "foobar"
        - myapp
destination:
  github:    
    - token_file: /gickup/github-token.txt # alternatively, specify token in a file
    # - token_file: github-token.txt # alternatively, specify token in a file
      organization: defyjoy   
      force: true
      visibility:
        repositories: private # private, public, default: private

log: # optional
  timeformat: 2006-01-02 15:04:05 
  file-logging: # optional
    dir: log # directory to log into
    file: gickup.log # file to log into
    maxage: 7 # keep logs for 7 days
```
Here are the gitlab token permissions - 

![image](https://github.com/cooperspencer/gickup/assets/1047068/b6a311f2-cc30-4e25-97dc-670f1517b24e)

**Comment by cooperspencer** [comment]
Hi,
I'll have a look and get back to you on that.

**Comment by cooperspencer** [comment]
I had a look and ran into the same issue as you did. Solution for me was to add the `user` parameter to my gitlab config.
For the next release I'll try to find the tokens user, so that you don't need to add that in the future anymore.

```yaml
source:
  gitlab:
    # - token_file: /gickup/gitlab-token.txt
    # - token_file: gitlab-token.txt
    - ssh: false # can be true or false
      user: your-username
      # username: myemail@gmail.com
      token: glpat-abczyx
      includeorgs: 
        - myapp
      include: # this includes the repo "foobar"
        - myapp
```

**Comment by defyjoy** [comment]
OK so I tried to fill in `user` with both the username in gitlab eg: `defyjoy1212343`  or my email . Both didn't work . What is the user we should be putting there ?

**Comment by cooperspencer** [comment]
It should be your gitlab username. I just committed code to the `main` branch to automatically get your username, via the token, if not specifically mentioned in the config file.
You can try to run that via the docker containers `buddyspencer/gickup:dev` or `docker pull buddyspencer/gickup:ubuntu-dev`

**Comment by defyjoy** [comment]
So this time it got weirder . It did receive the username from `buddyspencer/gickup:dev` but look at that duration. It took almost 19 minutes and was doing nothing  - 
```
╰─(base) ○ docker compose up
[+] Building 0.0s (0/0)                                                                                                                  docker:desktop-linux
[+] Running 1/0
 ✔ Container myapp-gickup-runner-1  Created                                                                                                           0.0s
Attaching to myapp-gickup-runner-1
myapp-gickup-runner-1  | 2024-01-25T16:02:37+05:30 INF Reading /gickup/conf.yml file=/gickup/conf.yml
myapp-gickup-runner-1  | 2024-01-25 16:02:37 INF Configuration loaded destinations=1 pairs=1 sources=1
myapp-gickup-runner-1  | 2024-01-25 16:02:37 INF Backup run starting
myapp-gickup-runner-1  | 2024-01-25 16:02:38 INF grabbing repositories from myusername1234 stage=gitlab url=https://gitlab.com
myapp-gickup-runner-1  | 2024-01-25 16:02:45 INF starting backup for https://gitlab.com/myapp/myapp.git stage=backup
myapp-gickup-runner-1  | 2024-01-25 16:02:45 INF mirroring myapp to https://github.com stage=github url=https://github.com

myapp-gickup-runner-1  | 2024-01-25 16:21:37 ERR authentication required stage=tempclone url=https://gitlab.com/myapp/myapp.git
myapp-gickup-runner-1  | 2024-01-25 16:21:41 INF Backup run complete duration=19m3.891281938s
myapp-gickup-runner-1 exited with code 0
```
The `conf.yaml` . I have removed the user since it's fetched automatically - 

```
source:
  gitlab:
    # - token_file: /gickup/gitlab-token.txt # This stores the github token
    # - token_file: gitlab-token.txt # This stores the github token
    - ssh: false # can be true or false
      token: "glpat-abcxyz"
      includeorgs: # this includes repos from the organizations "foo1" and "bar1"
        - myapp
      include: # this includes the repo "foobar"
        - myapp
destination:
  github:    
    - token_file: /gickup/github-token.txt # alternatively, specify token in a file
    # - token_file: github-token.txt # alternatively, specify token in a file
      organization: myapp   
      force: true
      visibility:
        repositories: private 
log: # optional
  timeformat: 2006-01-02 15:04:05 # you can use a custom time format, use https://yourbasic.org/golang/format-parse-string-time-date-example/ to check how date formats work in go
                                  # or set it as environment variable GICKUP_TIME_FORMAT
  file-logging: # optional
    dir: log # directory to log into
    file: gickup.log # file to log into
    maxage: 7 # keep logs for 7 days
```

If a gitlab has a project , do we include the same in `includeorgs` ? 

I am not very sure where am I wrong .

**Comment by cooperspencer** [comment]
the step "mirrorin myapp to https://github.com" contains the local clone and then the push to Github. Weird that it takes so long, is it a very large repo?

The authentication required seems to be coming from github directly. I will do more investigation on that, but I can reproduce the problem.

**Comment by defyjoy** [comment]
If the authentication issue is coming from github I can create a new PAT token and see if it works . I was confused if the authentication failed on gitlab side.

**Comment by defyjoy** [comment]
Ok so I tried with a new token on github and gitlab both does not work . Yes the repo is on larger side but this time it took around 1minute around .

**Comment by cooperspencer** [comment]
I found the error... I didn't add the authentication during the `git fetch`. You can retry it with the `dev` containers

**Comment by defyjoy** [comment]
Great work !! However one last issue. I am able to work through other smaller repos but this one a pretty heavy one and receiving the message - 

```
myapp-gickup-runner-1  | 2024-01-26 07:23:09 INF mirroring myapp to https://github.com stage=github url=https://github.com
myapp-gickup-runner-1  | 2024-01-26 07:24:25 ERR some refs were not updated stage=tempclone url=https://gitlab.com/myapp/myapp.git
myapp-gickup-runner-1  | 2024-01-26 07:24:37 INF Backup run complete duration=1m32.857118001s
```

Anyway to get around this ? When I clone it on my local it doesn't throw tantrums of course .

**Comment by cooperspencer** [comment]
That is a great use case because I don't have such big repositories, so thanks a lot for testing it so extensively.
I created a new container for this issue: `buddyspencer/gickup:issue_200`

After some digging, I found that someone had a similar issue with `go-git` and there solution was to add `Force: true` to `git fetch`. I added that to this branch. Can you please use `buddyspencer/gickup:issue_200` and test if it works?

**Comment by defyjoy** [comment]
Went quite far but not quite . I received this error now - 

```
myapp-gickup-runner-1 ERR command error on refs/heads/release-myapp-one: pre-receive hook declined stage=github url=https://gitlab.com/myapp/myapp.git
myapp-gickup-runner-1  | 2024-01-26 12:42:50 INF Backup run complete duration=9m34.106607763s
```

**Comment by cooperspencer** [comment]
damn, this is a hard one. Is gickup able to backup this repo locally? So instead of using `github` as destination can you try to use `local` and tell me if that works?

**Comment by defyjoy** [comment]
Thanks for responding so quick . So yes there is absolutely no issue in backing up locally . 

```
myapp-gickup-runner-1  | 2024-01-26T13:20:41+05:30 INF Reading /gickup/conf.yml file=/gickup/conf.yml
myapp-gickup-runner-1  | 2024-01-26 13:20:41 INF Configuration loaded destinations=1 pairs=1 sources=1
myapp-gickup-runner-1  | 2024-01-26 13:20:41 INF Backup run starting
myapp-gickup-runner-1  | 2024-01-26 13:20:42 INF grabbing repositories from joydeep7840104 stage=gitlab url=https://gitlab.com
myapp-gickup-runner-1  | 2024-01-26 13:20:46 INF starting backup for https://gitlab.com/myapp/myapp.git stage=backup
myapp-gickup-runner-1  | 2024-01-26 13:20:46 INF cloning gitlab.com/myapp/myapp.git/1706255446 path=/gickup/backup stage=locally
myapp-gickup-runner-1  | 2024-01-26 13:21:48 INF zipping gitlab.com/myapp/myapp.git/1706255446 path=/gickup/backup stage=locally
myapp-gickup-runner-1  | 2024-01-26 13:21:53 INF Backup run complete duration=1m12.177087158s
```

The destination config 
```
destination:
  local:
    - path: /gickup/backup
      structured: true
      zip: true
      keep: 5
      bare: true
```

Docker compose mounted volume 

````
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml # Change the path of your local config ${PWD} is your current directory (where the docker-compose.yml is located)
      - ${PWD}/gitlab-token.txt:/gickup/gitlab-token.txt
      - ${PWD}/github-token.txt:/gickup/github-token.txt
      - ${PWD}/tmp:/tmp/
      - ${PWD}/backup:/gickup/backup
```

And the zipped file got created

**Comment by cooperspencer** [comment]
I pushed a new container on `buddyspencer/gickup:issue_200`. It won't fix the issue but hopefully tells me where it comes from. Can you please post the error message afterwards?

**Comment by defyjoy** [comment]
Ok so I removed the stale docker container and rerun to pull the new image however the issue remains the same and no information provided too . 

```
myapp-gickup-runner-1  | 2024-01-26 14:30:29 ERR command error on refs/heads/release-myapp-one: pre-receive hook declined git=push stage=github url=https://gitlab.com/myapp/myapp.git
myapp-gickup-runner-1  | 2024-01-26 14:30:42 INF Backup run complete duration=9m43.378001265s
```

**Comment by cooperspencer** [comment]
It comes from the push. Can you check if you have any pre-receive hooks on your repo?

**Comment by defyjoy** [comment]
> It comes from the push. Can you check if you have any pre-receive hooks on your repo?
Which repo ? Github or Gitlab ?

**Comment by cooperspencer** [comment]
doesn't matter actually. does your repo have a `.git/hooks` directory?

**Comment by cooperspencer** [comment]
can you check if any of the hooks in there give you issues regarding pushing the code? also try to remove the force parameter from the github push.

**Comment by defyjoy** [comment]
I tried creating one branch and pushing it . It doesn't seem to fail . If thats what you wanted to ask

**Comment by cooperspencer** [comment]
```yaml
destination:
  github:    
    - token_file: /gickup/github-token.txt # alternatively, specify token in a file
    # - token_file: github-token.txt # alternatively, specify token in a file
      organization: defyjoy   
      force: false
      visibility:
        repositories: private # private, public, default: private
```
the other question was if there is actually anything in the hooks directory
