### ISSUE TITLE
Clone public repos without authentication

### ISSUE THREAD

**Issue by zhulik** [cooperspencer/gickup#21]
Hello,

thanks for building such a useful tool!

Is there a way to backup all public repos belonging to a user without authentication?

Thank you!

**Comment by cooperspencer** [comment]
Hi,
you are welcome.
Sure, you can clone without authentication, you just have to add the user to the config like this:
```yaml
source:
  github:
    - user: cooperspencer
destination:
  local:
    - path: /home/andy/backup

```

that should be it. Should you still run into troubles, please tell me.
