### ISSUE TITLE
Latest docker image (0.10.27) causes infinite config reload

### ISSUE THREAD

**Issue by miped** [cooperspencer/gickup#210]
Just filled up my disk with logging. It logs _very fast_ as you can see from the timestamps: 

![image](https://github.com/cooperspencer/gickup/assets/22974/af220de0-d531-4af4-b129-b840bbfe76e3)

Reverting to 0.10.26 fixed it. I think i've got a pretty standard setup:

```yaml
- name: Add gickup container
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: gickup
    image: buddyspencer/gickup:latest
    pull: true
    networks:
      - name: development
    purge_networks: true
    networks_cli_compatible: false
    volumes:
      - "{{ gickup_data_directory }}:/data:rw"
      - "{{ gickup_ssh_directory }}:/.ssh/:rw"
    env:
      TZ: "{{ nas_timezone }}"
    command: /data/conf.yml
    restart_policy: unless-stopped
    memory: 1g
```

**Comment by cooperspencer** [comment]
Can you share your config with me? Just redact the tokens. I had the issue in my tests but I thought I fixed it...

**Comment by miped** [comment]
> Can you share your config with me? Just redact the tokens. I had the issue in my tests but I thought I fixed it...

Here you go:

```yaml
---
cron: 0 1 * * *  # 1am daily

source:
  github:
    - token: "{{ gickup_github_token }}"
      ssh: true
      sshkey: "{{ gickup_ssh_key }}"

destination:
  gitea:
    - token: "{{ gickup_gitea_token }}"
      createorg: true
      url: "http://gitea:3000/"
      mirrorinterval: 8h

---

source:
  github:
    - token: "{{ gickup_github_token }}"
      ssh: true
      sshkey: "{{ gickup_ssh_key }}"

destination:
  local:
    - path: /data/local/
      structured: true

metrics:
  heartbeat:
    urls:
      - "{{ gickup_healthcheck }}"
```
