### ISSUE TITLE
path segment [0] is empty stage=gitea 

### ISSUE THREAD

**Issue by ogdabou** [cooperspencer/gickup#239]
Hello,

Thanks for this !

I'm trying to backup gitea to Github an get the following error :

```
2024-05-08T11:57:26Z ERR path segment [0] is empty stage=gitea url={REDACTED}
```

I'm not sure to understand wwhat I should change

My configuration looks like this : 
```
source:
  gitea:
    - url: xx
      username: xx
      password: xx
      wiki: false
      starred: true
      ssh: false
  #    issues: true
      filter:
        excludearchived: true
        excludeforks: true
destination:
  github:
    - organization: xx
      force: true
      visibility:
        repositories: private
      token: xx
```

The values between `{{}}` are redacted, they are provided for Gickup `0.10` running in a container

Do you know what I'm missing or providing wrongly ?

Thanks a lot :)
