### ISSUE TITLE
Port 443 connection refused with gickup, gitea, and traefik

### ISSUE THREAD

**Issue by Aetherinox** [cooperspencer/gickup#242]
Hey, looking to see if I can get some direction here.

Recently I moved my system from bare metal over to docker and traefik. 
Within the gickup console, I've noticed the following error:

```
2024-06-01 16:22:57 INF Read token file bytes=41 path=/gickup/tokens/gitea.txt

2024-06-01 16:22:57 ERR Get "https://git.mydomain.com/api/v1/version": dial tcp 172.18.0.20:443: connect: connection refused stage=gitea url=https://git.mydomain.com
```

The odd thing is that if I look at my Gitea repos, it does appear to still be syncing, but this error gets thrown right before every single repo goes to sync.

I've ensured Traefik has port 443 open, I've set up SSH port 22, I even tried using docker `expose: 443` between gickup and gitea, and nothing seems to be working.

**Comment by Aetherinox** [comment]
Another update. It appears I get two different results depending on which CURL I use

**Works**

```
curl "https://git.domain.com/api/v1/version" \
    -H "accept: application/json" \
    -H "Authorization: token MYTOKEN" -i
```

**Connection Refused**
```
curl "https://172.18.0.20:443/api/v1/version" \
    -H "accept: application/json" \
    -H "Authorization: token MYTOKEN" -i
```

But I'm not sure where it's pulling the IP from so that I can change it. Or how to open the local IP.

**Comment by Aetherinox** [comment]
Another update, in case you have anything to add, it would be helpful. Would like to know why this initially happened.

I went back into my `conf.yml` and changed the `url` from my domain, to the localhost ip / port for `gitea`:

```yml
destination:
  gitea:
      url: https://mydomain.com
```

**Changed To:**
```yml
destination:
  gitea:
      url: http://172.18.0.20:3000/
```

This seemed to stop the error all together, and it is now syncing without any mention of a connection being refused. Not sure why though. Seeing as I couldn't curl locally earlier.

**Comment by cooperspencer** [comment]
The only thing I can think of is a problem within the DNS settings.

You said that Gitea is still mirroring. That is normal, Gickup uses Giteas' API to create a mirror and Gitea handles this mirror and resyncs it according to your configured interval.

I will try to recreate your setup and see if I can find out what's going on.
So you use docker and run Traefik, Gitea and Gickup?

**Comment by cooperspencer** [comment]
What you could try as well, is to use the name of your gitea container in gickups' config file. Like 'http://gitea:3000'

**Comment by Aetherinox** [comment]
Yeah would be interesting to know. I've triple checked my settings.
I'm running:
- Docker
- Traefik
- Gitea
- Gickup

All current versions. 

I'll provide the composer files below. I took out the stuff like ElasticSearch since it's useless here:

### Gickup

#### docker-compose.yml

```yml
services:

  gickup:
    container_name: "gickup"
    image: buddyspencer/gickup:latest
    hostname: gickup.${SERVER_DOMAIN}
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml
      - ${PWD}/backup:/gickup/backup
      - ${PWD}/logs:/gickup/logs
      - ${PWD}/tokens/gitea.txt:/gickup/tokens/gitea.txt
      - ${PWD}/tokens/github.txt:/gickup/tokens/github.txt
    command: ["/gickup/conf.yml"]
    environment:
        PUID: ${UID}
        PGID: ${GID}
    networks:
      traefik:
        ipv4_address: "${SERVICE_IP}"
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik
      - traefik.docker.network=${SERVER_NETWORK}

      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

      - traefik.http.routers.gickup-http.rule=Host(`gickup.localhost`) || Host(`gickup.${SERVER_DOMAIN}`) || Host(`www.gickup.${SERVER_DOMAIN}`) || Host(`${SERVICE_IP}`)
      - traefik.http.routers.gickup-http.service=gickup
      - traefik.http.routers.gickup-http.entrypoints=http
      - traefik.http.routers.gickup-http.priority=1
      - traefik.http.routers.gickup-http.middlewares=https-redirect

      - traefik.http.routers.gickup-https.rule=Host(`gickup.localhost`) || Host(`gickup.${SERVER_DOMAIN}`) || Host(`www.gickup.${SERVER_DOMAIN}`) || Host(`${SERVICE_IP}`)
      - traefik.http.routers.gickup-https.service=gickup
      - traefik.http.routers.gickup-https.entrypoints=https
      - traefik.http.routers.gickup-https.priority=1
      - traefik.http.routers.gickup-https.tls=true
      - traefik.http.routers.gickup-https.tls.certresolver=cloudflare
      - traefik.http.routers.gickup-https.tls.domains[0].main=${SERVER_DOMAIN}
      - traefik.http.routers.gickup-https.tls.domains[0].sans=*.${SERVER_DOMAIN}

      - traefik.http.services.gickup.loadbalancer.server.port=443
      - traefik.http.services.gickup.loadbalancer.server.scheme=https

networks:
  traefik:
    name: ${SERVER_NETWORK}
    external: true
```

#### Gickup .env

```env
SERVER_DOMAIN=domain.com
SERVER_IP=XX.XX.XX.XX
SERVER_NETWORK=traefik

UID=143
GID=997

SERVICE_IP=172.18.0.9
```

---

### Gitea

#### docker-compose.yml:

```yml
services:
  gitea:
    container_name: gitea
    image: gitea/gitea
    hostname: git.${SERVER_DOMAIN}
    restart: always
    networks:
      traefik:
        ipv4_address: "${GITEA_IP}"
    environment:
      PUID: ${UID}
      PGID: ${GID}
      USER_UID: ${UID}
      USER_GID: ${GID}
      GITEA__database__DB_TYPE: '${GITEA_DB_TYPE}'
      GITEA__database__HOST: '${GITEA_DB_HOST}'
      GITEA__database__NAME: '${GITEA_DB_NAME}'
      GITEA__database__USER: '${GITEA_DB_USER}'
      GITEA__database__PASSWD: '${GITEA_DB_PASS}'
      GITEA_CUSTOM: '${GITEA_DIR_CUSTOM}'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik
      - traefik.docker.network=${SERVER_NETWORK}

      - traefik.http.routers.gitea-http.rule=Host(`git.localhost`) || Host(`git.${SERVER_DOMAIN}`) || Host(`www.git.${SERVER_DOMAIN}`) || Host(`${GITEA_IP}`)
      - traefik.http.routers.gitea-http.service=gitea
      - traefik.http.routers.gitea-http.entrypoints=http
      - traefik.http.routers.gitea-http.middlewares=https-redirect@file

      - traefik.http.routers.gitea-https.rule=Host(`git.localhost`) || Host(`git.${SERVER_DOMAIN}`) || Host(`www.git.${SERVER_DOMAIN}`) || Host(`${GITEA_IP}`)
      - traefik.http.routers.gitea-https.service=gitea
      - traefik.http.routers.gitea-https.entrypoints=https
      - traefik.http.routers.gitea-https.tls=true
      - traefik.http.routers.gitea-https.tls.certresolver=cloudflare
      - traefik.http.routers.gitea-https.tls.domains[0].main=${SERVER_DOMAIN}
      - traefik.http.routers.gitea-https.tls.domains[0].sans=*.${SERVER_DOMAIN}

      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.services.gitea.loadbalancer.server.scheme=http

      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitea-ssh.entrypoints=gitea-ssh      
      - traefik.tcp.routers.gitea-ssh.tls=true
      - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22

networks:
  traefik:
    name: ${SERVER_NETWORK}
    external: true

```

<br />

#### Gitea .env:

```env
SERVER_DOMAIN=domain.com
SERVER_IP=XX.XX.XX.XX
SERVER_NETWORK=traefik

UID=143
GID=997

GITEA_IP=172.18.0.20
GITEA_DB_TYPE=mysql
GITEA_DB_HOST=mariadb:3306
GITEA_DB_NAME=XXXXX
GITEA_DB_USER=XXXXX
GITEA_DB_PASS=XXXXX
GITEA_DIR_CUSTOM=/data/custom
```

<br />

### Traefik Static File:

The Traefik `traefik.yml` static file is the typical file, just with this added:

```yml
entryPoints:
  gitea-ssh:
    address: :22/tcp
```

**Comment by Aetherinox** [comment]
Thanks. http://gitea:3000 works. I should have done it earlier anyway, but I've worked on this issue since I initially put in the issue report, so my brain is fried for the day.

**Comment by marcuswoy** [comment]
@Aetherinox, Could you share your latest changes to make http://gitea:3000 possible? I appreciate it.

**Comment by Aetherinox** [comment]
Sorry, been a month since I wrote this, brain needs refreshing.

In my gickup `config.yml` I used
```yml
destination:
  gitea:
    - token_file: /gickup/tokens/gitea.txt
      user: xxxxxxx
      url: http://gitea:3000/                  <--------
      createorg: true
      mirrorinterval: 1h0m0s
      lfs: false
      visibility:
        repositories: private
        organizations: private
```

`gitea` is the name of the docker container, so out of box, you should be able to call any container by its name within other configs.
