### ISSUE TITLE
Support for Apprise push gateway

### ISSUE THREAD

**Issue by armond-avanes** [cooperspencer/gickup#243]
It would be great if we could have the support for Apprise notifications (as push gateway), which adds the support to many popular platforms. Not sure if it can be directly integrated since it's written in Python: https://github.com/caronc/apprise

But there is also another project from Apprise author which wraps this framework in a RESTful API. If you support its format (which is basically a POST with JSON body), anyone hosting this RESTful API will be able to reach tens of different notification platforms: https://github.com/caronc/apprise-api

**Comment by cooperspencer** [comment]
I'll have a look. Doesn't seem too complicated to integrate.

**Comment by armond-avanes** [comment]
@cooperspencer Thanks for considering this feature. Please let me know if you need any help testing this.

**Comment by armond-avanes** [comment]
@cooperspencer Is there any update or ETA for this feature request?

**Comment by cooperspencer** [comment]
I'd like to have it in the upcoming or following release.

**Comment by armond-avanes** [comment]
Thank you for the update.

**Comment by cooperspencer** [comment]
I finally started with it. It already works. I need to document it in conf.example.yaml and let it return the error if there is one.

You can have a look at the progress in this MR:
https://github.com/cooperspencer/gickup/pull/309

**Comment by armond-avanes** [comment]
@cooperspencer Very exciting! Thanks for your efforts! Just a quick question since it's not super clear from the docs (or maybe I'm missing something)... Does Gickup only send notifications in the case of error? Or it's like on any event (successful completion, error, etc)?

**Comment by cooperspencer** [comment]
At the moment it only sends the duration of how long the run took. I have to change that with the next release.

**Comment by armond-avanes** [comment]
@cooperspencer I just want to confirm that Apprise integration is working pretty fine. Great job!

My only feedback for any kind of notification platform is to be more verbose and provide more information so that I can take a look at my notification and see what's going on. For example:
- WatchTower sends an immediate notification when it comes up for the first time to show that it's up and running and healthy (along with version information, the schedule and when is the next one). Something like what you're sending to the container logs, but to be published as a notification.
- I want to have more information on what repositories had changes to backup or at least a list of repos which have been backed up, in addition to the total running time. Something like:
  "X repositories were backed up:
    * repo-url-here: No changes to backup
    * repo2-url-here: X files were backed up. OR There were some changes to backup.
    The overall run took X seconds, etc, etc"
- If you don't have any error/warning notification in the case of errors, it's very important to have; and to list which repo(s) the errors/warnings are about.

**Comment by cooperspencer** [comment]
Thanks a lot for the feedback and I am glad it works for you.

You are absolutely right, the output needs to be more verbose. I will fix that with the next release. It won't take as long as the last one.

**Comment by vonpupp** [comment]
Hi,

I am unsure how to use apprise. 

My config looks like this:
```
version: 1
urls:
  - tgram://$TOKEN/$CHAT:
    - tag: default
  - tgram://$TOKEN/$CHAT:
    - tag: gitlab
  - tgram://$TOKEN/$CHAT:
    - tag: github
```

I have been able to use on the terminal on the host machine (I haven't tried that within the container) with the following line: 
apprise -vvv --config apprise.yml --tag=gitlab --body="gitlab trigger"

This is how the gickup apprise section looks like:
```
push:
  apprise:
    - url: http://<apprise-api-container-name>:8000
      # config: /config/apprise.yaml # Unsure about this, I don't know if it is the location of the config within the container, or just as a client?
      tags:
        - gitlab
      #notification_urls:
      #  - tag://gitlab-backup # This was generated by chatgpt, I don't think is accurate.
```

How would you write the config section?

I am using gickup within a docker container. Do you need to have an apprise-api docker container up and running and use that as the URL?

Thanks!

**Comment by cooperspencer** [comment]
Hi,

so the `config` isn't a yaml file. This is the ID for the configuration in Apprise. When you initialise apprise I think it generates a unique ID for the set of configuration and that ID needs to go into the `config` field. I hope that cleared it up.

**Comment by vonpupp** [comment]
Thanks for your response.

Sadly I am not able to use it. It may be several problems. I am not fluent in go. I was wondering if is there is a way to trigger this manually by inspecting the docker container. Kind of a minimal example. I suspect that I may have DNS resolution issues between the containers. I am running gickup on one container and apprise on another one.

For instance, this works fine from the host that runs the containers:
```
curl -X POST \
    -F "body=Test Message" \
    -F "tags=all" \
    http://localhost:8000/notify/apprise
```

My gickup config looks like this:
```
push:
  apprise:
    - url: http://localhost:8000
      config: apprise
      tags:
        - gitlab
```

My apprise config looks like this:
```
version: 1
urls:
  - tgram://$TOKEN/$CHAT:
    - tag: default
  - tgram://$TOKEN/$CHAT:
    - tag: gitlab
  - tgram://$TOKEN/$CHAT:
    - tag: github
```

The apprise config is http://localhost:8000/cfg/apprise, so I assume that the config section that I need to use on the push config as you suggested prior is "apprise".
