### ISSUE TITLE
should gickup error on unknown keywords

### ISSUE THREAD

**Issue by vic1707** [cooperspencer/gickup#249]
When testing configs for the purpose explained in #248 I went and tried 

```
# ...
source:
    github:
        # ....
        - organization: Zelda-Reverse-Engineering-Team
          token_file: /config/token # fine grained token for vic1707
```

And realized that everything my token had access to was getting downloaded. Shouldn't gickup have some kind of config checks and error on invalid/malformed config ?

First I went crazy speculating some cache was messing with me when it was simply a missconfig and gickup was ignoring `organization: Zelda-Reverse-Engineering-Team` (tried `user` before but didn't do the trick)
