### ISSUE TITLE
"couldn't find any repositories for user"

### ISSUE THREAD

**Issue by greysonp** [cooperspencer/gickup#292]
Hi there! I was trying out the tool, and I ran into the following error:

```
2025-02-04T21:53:41Z INF Reading conf.yml file=conf.yml
2025-02-04T21:53:41Z INF Configuration loaded destinations=1 pairs=1 sources=1
2025-02-04T21:53:41Z INF Backup run starting
2025-02-04T21:53:41Z INF grabbing repositories from greyson stage=sourcehut url=https://git.sr.ht/
2025-02-04T21:53:41Z ERR couldn't find any repositories for user ~greyson stage=sourcehut url=https://git.sr.ht/
2025-02-04T21:53:41Z INF Backup run complete duration=284.313772ms
```

But there _are_ repositories for this user, i.e. https://git.sr.ht/~greyson/

Here's the output of my log file:

```
{"level":"info","sources":1,"destinations":1,"pairs":1,"time":"2025-02-04T21:53:41Z","message":"Configuration loaded"}
{"level":"info","time":"2025-02-04T21:53:41Z","message":"Backup run starting"}
{"level":"info","stage":"sourcehut","url":"https://git.sr.ht/","time":"2025-02-04T21:53:41Z","message":"grabbing repositories f
rom greyson"}
{"level":"error","stage":"sourcehut","url":"https://git.sr.ht/","time":"2025-02-04T21:53:41Z","message":"couldn't find any repo
sitories for user ~greyson"}
{"level":"info","duration":"284.313772ms","time":"2025-02-04T21:53:41Z","message":"Backup run complete"}
```

Here's my config:

```yml
source:
        sourcehut:
                - user: greyson
                  username: greyson
                  password: <hidden>

destination:
        local:
                - path: <hidden>

log:
        file-logging:
                dir: <hidden>
                file: gickup.log
                maxage: 7
```

I've tried lots of different combinations, including settings (token, user, username, password), all the way down to just (user) or just (token). Always the same result.

Thanks!

**Comment by cooperspencer** [comment]
Hi there,

I'll have a look and get back to you.

**Comment by cooperspencer** [comment]
I think the problem is that I only tested it with legacy tokens, which they disabled at some point. I have to investigate on how to make it work again, because I also don't get the rest api to work with the tokens.

**Comment by cooperspencer** [comment]
as a quick and dirty fix, you can create a personal access token via https://meta.sr.ht/oauth/personal-token and use it via
```yaml
source:
        sourcehut:
                - token: <previously generated token>

destination:
        local:
                - path: <hidden>

log:
        file-logging:
                dir: <hidden>
                file: gickup.log
                maxage: 7
```

I still have to figure out how to use the new tokens to authenticate via the API. But I think that will help you for now.
