### ISSUE TITLE
Error: `lstat /var/lib/git-archive/archive/github.com/..../1739241006: no such file or directory`

### ISSUE THREAD

**Issue by Ramblurr** [cooperspencer/gickup#294]
I had gickup running for awhile, but somewhere along the line something broke and I'm not sure what or when exactly.

Gickup is running and claims to complete succesfully (`INF Backup run complete duration=6.607920739s`), but it is not in fact archving any git repos and instead is creating empty zip files.

## Config

```yaml
---
source:
  github:
    - token: redacted
      user: ramblurr
      ssh: false
      filter:
        lastactivity: 2y
        excludeforks: true
destination:
  local:
    - path: /var/lib/git-archive/archive
      structured: true
      zip: true
      keep: 5
      bare: true
      lfs: false

log: # optional
  file-logging: # optional
    dir: /var/lib/git-archive/logs
    file: gickup.log
    maxage: 7

```

## Log extract

Every repo has a pattern like this:

```jsonl
{"level":"info","stage":"backup","time":"2025-02-11T03:30:06+01:00","message":"starting backup for https://github.com/Ramblurr/probematic.git"}
{"level":"info","stage":"locally","path":"/var/lib/git-archive/archive","time":"2025-02-11T03:30:06+01:00","message":"cloning github.com/Ramblurr/probematic.git/1739241006"}
{"level":"info","stage":"locally","path":"/var/lib/git-archive/archive","time":"2025-02-11T03:30:06+01:00","message":"zipping github.com/Ramblurr/probematic.git/1739241006"}
{"level":"error","stage":"locally","path":"/var/lib/git-archive/archive","repo":"github.com/Ramblurr/probematic.git/1739241006","time":"2025-02-11T03:30:06+01:00","message":"lstat /var/lib/git-archive/archive/github.com/Ramblurr/probematic.git/1739241006: no such file or directory"}
{"level":"info","stage":"backup","time":"2025-02-11T03:30:06+01:00","message":"starting backup for https://github.com/Ramblurr/Quechua.git"}
{"level":"info","stage":"locally","path":"/var/lib/git-archive/archive","time":"2025-02-11T03:30:06+01:00","message":"cloning github.com/Ramblurr/Quechua.git/1739241006"}
{"level":"info","stage":"locally","path":"/var/lib/git-archive/archive","time":"2025-02-11T03:30:06+01:00","message":"zipping github.com/Ramblurr/Quechua.git/1739241006"}
{"level":"error","stage":"locally","path":"/var/lib/git-archive/archive","repo":"github.com/Ramblurr/Quechua.git/1739241006","time":"2025-02-11T03:30:06+01:00","message":"lstat /var/lib/git-archive/archive/github.com/Ramblurr/Quechua.git/1739241006: no such file or directory"}
```

## Empty archive files

```console
# ls  /var/lib/git-archive/archive/github.com/Ramblurr/Quechua.git/
... snip .. I should prune old backups ...
-rw-------  1 63584 63584  22 Feb  7 03:30 1738895408.zip
-rw-------  1 63584 63584  22 Feb  8 03:30 1738981813.zip
-rw-------  1 63584 63584  22 Feb  9 03:30 1739068206.zip
-rw-------  1 63584 63584  22 Feb 10 03:30 1739154606.zip  
-rw-------  1 63584 63584  22 Feb 11 03:30 1739241006.zip # <---- that is today!
```

Note the size on all those files, basically nothing. unzipping them reveals:

```console
[root@dewey:~/test]# unzip 1739241006.zip 
Archive:  1739241006.zip
warning [1739241006.zip]:  zipfile is empty
```

All my archives are empty!
```console
$ find /var/lib/git-archive/archive -type f -size -50c | wc -l
4661  # 😲
```

(You can ignore the funny uid, I am running gickup in a systemd service with [DynamicUser=](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#DynamicUser=))

```
$ gickup --version
0.10.36
```
