### ISSUE TITLE
SSH known_hosts error, but only with cron schedule

### ISSUE THREAD

**Issue by redjax** [cooperspencer/gickup#295]
When I run gickup in docker compose, I get the error 'ssh: handshake failed: knownhosts: key is unknown' or an error about being unable to find a known_hosts file. This only happens when I include a cron schedule in my config.

This is my docker compose file:

```yaml
---
networks:
  gickup_net: {}

volumes:
  gickup_logs: {}
  gickup_local_backups: {}

services:
  gickup:
    image: buddyspencer/gickup:${GICKUP_VERSION:-latest}
    container_name: gickup
    restart: unless-stopped
    volumes:
      - ${GICKUP_CONFIG:-./config/default.yml}:/gickup/conf.yml
      ## If using /backup/ in the container for local destination,
      #  mount it in a volume for persistence
      - ${GICKUP_BACKUP_DIR:-gickup_local_backups}:/backup
      ## Mount an SSH key, i.e. ~/.ssh/gickup_id_rsa
      #  Create a key with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/gickup_id_rsa -N ""
      - ${GICKUP_SSH_KEY}:/.ssh/id_rsa:ro
      ## Mount logging path to persist logs
      - ${GICKUP_LOGS_DIR:-gickup_logs}:/log
      ## Mount a Github PAT
      - ${GICKUP_GITHUB_PAT_FILE}:/.ssh/github_token:ro
      ## Mount a gitea/forgejo/codeberg PAT
      - ${GICKUP_CODEBERG_PAT_FILE}:/.ssh/codeberg_token:ro
      ## If you get errors about the container not being able to find a known_hosts file,
      #  create a file called 'known_hosts' in the same path as the compose.yml file and
      #  uncomment this volume mount.
      - ${GICKUP_KNOWN_HOSTS:-./known_hosts}:/.ssh/known_hosts
    command: ["/gickup/conf.yml"]
    environment:
      TZ: ${TZ:-Etc/UTC}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - gickup_net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    pull_policy: always
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the
      #  "com.centurylinklabs.watchtower.enable=true" label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gickup_net

```

And my `.env` file:

```plaintext
## Default: latest
GICKUP_VERSION=
## Default: ./config/default.yml
GICKUP_CONFIG=./config/backups.yml
## Default: (named volume) gickup_local_backups
GICKUP_BACKUP_DIR=./backup
## Default: (named volume) gickup_logs
GICKUP_LOGS_DIR=./logs
## Default: Etc/UTC
TZ=
## Default: (none/unset)
GICKUP_SSH_KEY=./secrets/ssh_keys/gickup_id_rsa
## Default: (none/unset)
GICKUP_GITHUB_PAT_FILE=./secrets/tokens/github_token
## Default: (none/unset)
GICKUP_CODEBERG_PAT_FILE=./secrets/tokens/codeberg_token

```

The github_token and codeberg_token were created on each respective remote's site and copied to my gickup directory. I generated an SSH key for gickup using `ssh-keygen -t rsa -b 4096 -f ./secrets/ssh_keys/gickup_id_rsa` and uploaded the public key to both Github and Gickup.

This is the gickup config I'm mounting in the container:

```yaml
## Crontab schedule to run gickup
# cron: "*/15 * * * *"

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - url: "git@github.com:redjax"
      ssh: true
      ## Path in container
      key: "/.ssh/id_rsa"
      token_file: "/.ssh/github_token"
      ## Names of repositories to include
      include:
        - "repo1"
        - "repo2"
      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: true
      issues: true
      filter:
        # lastactivity: 1y
        excludearchived: true
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  codeberg:
    - url: git@codeberg.com:redjax
      user: redjax
      token_file: /.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: false
      visibility:
        repositories: private
        organizations: private
      force: true

  ## Backup to an S3 bucket
  # s3:
  #   - endpoint: somewhere:9000
  #     structured: true
  #     bucket: bucket-name
  #     accesskey: your-access-key
  #     secretkey: your-secret-key
  #     usessl: true

  ## Backup to a Gitlab repository
  # gitlab:
  #   - token: some-token
  #     token_file: token.txt
  #     url: http(s)://url-to-gitlab
  #     force: true
  #     mirror:
  #       enabled: true

  ## Backup to Github repository
  # github:
  #   - token: some-token
  #     token_file: token.txt
  #     organization: myorg
  #     force: true
  #     visibility:
  #       repositories: private

```

When I run this without a cron schedule, it sporadically works, or throws this error:

```shell
gickup  | 2025-02-14 01:07:09 WRN retry 2 from 5 error="read /.ssh/known_hosts: is a directory" path=/backup/ repo=red-utils stage=locally
```

I'm not sure what I've done wrong here, I had this working well for a period of time, but once I added a cron schedule, even if I comment it out, I'm not able to get gickup to synch my repositories anymore.

**Comment by cooperspencer** [comment]
Hi,
I'll have a look at it and get back to you.

**Comment by redjax** [comment]
Thank you, this tool is awesome :) I wrote a bunch of bash scripts to mirror my repos, but it's brittle and difficult to configure. This tool already works better than mine, even though I'm having this issue with SSH. 

If you need any info from me to help the investigation, let me know! :)

**Comment by cooperspencer** [comment]
I am really glad you like it. I built up a similar test setup to yours.
I had to mount the known_hosts file to /root/.ssh/known_hosts. That was it mostly.

On a quick side-note, I see that you have codeberg configured. There actually is no codeberg in the configuration of Gickup.
You can use Gitea and add your Codeberg configuration there. Codeberg runs on Forgejo, which is a fork of Gitea.
As for a mirror to Codeberg, you can have a look at this blogpost:
https://cooperspencer.github.io/gickup-documentation/blog/codeberg-mirror

If you still have problems, just reach out to me.

**Comment by redjax** [comment]
Thanks for the tips! I think I've made some progress :) I'm not seeing the known_hosts error anymore, I created an empty file and mounted it in the container and now it's movin'. This is my gickup config now:

```yaml
## Crontab schedule to run gickup
cron: "*/15 * * * *"

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - url: "git@github.com:redjax"
      ssh: true
      ## Path in container
      key: "/.ssh/id_rsa"
      token_file: "/.ssh/github_token"
      ## Names of repositories to include
      include:
        - "repo1"
        - "repo2"
      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: true
      issues: true
      filter:
        # lastactivity: 1y
        excludearchived: true
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  gitea:
    - url: git@codeberg.com:redjax
      user: redjax
      token_file: /.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: private
        organizations: private
      force: true
```

And my compose.yml:

```yaml
---
networks:
  gickup_net: {}

volumes:
  gickup_logs: {}
  gickup_local_backups: {}

services:
  gickup:
    image: buddyspencer/gickup:${GICKUP_VERSION:-latest}
    container_name: gickup
    restart: unless-stopped
    volumes:
      - ${GICKUP_CONFIG:-./config/default.yml}:/gickup/conf.yml
      ## If using /backup/ in the container for local destination,
      #  mount it in a volume for persistence
      - ${GICKUP_BACKUP_DIR:-gickup_local_backups}:/backup
      ## Mount an SSH key, i.e. ~/.ssh/gickup_id_rsa
      #  Create a key with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/gickup_id_rsa -N ""
      - ${GICKUP_SSH_KEY}:/.ssh/id_rsa:ro
      ## Mount logging path to persist logs
      - ${GICKUP_LOGS_DIR:-gickup_logs}:/log
      ## Mount a Github PAT
      - ${GICKUP_GITHUB_PAT_FILE}:/.ssh/github_token:ro
      ## Mount a gitea/forgejo/codeberg PAT
      - ${GICKUP_CODEBERG_PAT_FILE}:/.ssh/codeberg_token:ro
      ## If you get errors about the container not being able to find a known_hosts file,
      #  create a file called 'known_hosts' in the same path as the compose.yml file and
      #  uncomment this volume mount.
      - ${GICKUP_KNOWN_HOSTS:-./known_hosts}:/.ssh/known_hosts
    command: ["/gickup/conf.yml"]
    environment:
      TZ: ${TZ:-Etc/UTC}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - gickup_net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_gickup
    restart: unless-stopped
    pull_policy: always
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the
      #  "com.centurylinklabs.watchtower.enable=true" label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gickup_net

```

I think you were right about using gitea instead of codeberg, things are working again, but I can't tell if they're actually pushing to the Codeberg remote. I'm seeing repos cloned to the host mount I created, but when I run the container, I'm getting these logs now:

```
gickup  | 2025-02-19 10:22:01 INF mirroring transmissionpy to git@codeberg.com:redjax stage=gitea url=git@codeberg.com:redjax
gickup  | 2025-02-19 10:22:01 ERR stat /tmp: no such file or directory stage=tempclone url=https://github.com/redjax/transmissionpy.git
```

It seems like it's properly downloading/backing up my repos from Github, but I'm not seeing the changes mirrored to Codeberg yet. I'll keep tinkering around, but if you have any thoughts, I appreciate your help :)
