### ISSUE TITLE
Wrong 'dotfiles' repository being mirrored

### ISSUE THREAD

**Issue by redjax** [cooperspencer/gickup#296]
This is an interesting one...I am using gickup to mirror a number of repos, one of which is my 'dotfiles' repository. For reference, that is here: https://github.com/redjax/dotfiles

When gickup clones the source repository from Github, it is the correct dotfiles (i.e. redjax/dotfiles). However, when it mirrors to codeberg, something weird happens:

![Image](https://github.com/user-attachments/assets/ec2d2360-b8ee-47f0-9e74-6ffcd9689225)

Each time I delete the repository on codeberg and recreate it, I get a new user's dotfiles! It hasn't landed on mine yet 😝

For reference, here is my compose.yml:

```
---
networks:
  gickup_net: {}

volumes:
  gickup_logs: {}
  gickup_local_backups: {}

services:
  gickup:
    image: buddyspencer/gickup:${GICKUP_VERSION:-ubuntu-latest}
    container_name: gickup
    restart: unless-stopped
    volumes:
      - ${GICKUP_CONFIG:-./config/default.yml}:/gickup/conf.yml
      ## If using /backup/ in the container for local destination,
      #  mount it in a volume for persistence
      - ${GICKUP_BACKUP_DIR:-gickup_local_backups}:/backup
      ## Mount an SSH key, i.e. ~/.ssh/gickup_id_rsa
      #  Create a key with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/gickup_id_rsa -N ""
      - ${GICKUP_SSH_KEY}:/root/.ssh/id_rsa:ro
      ## Mount logging path to persist logs
      - ${GICKUP_LOGS_DIR:-gickup_logs}:/log
      ## Mount a Github PAT
      - ${GICKUP_GITHUB_PAT_FILE}:/root/.ssh/github_token:ro
      ## Mount a gitea/forgejo/codeberg PAT
      - ${GICKUP_CODEBERG_PAT_FILE}:/root/.ssh/codeberg_token:ro
      ## If you get errors about the container not being able to find a known_hosts file,
      #  create a file called 'known_hosts' in the same path as the compose.yml file and
      #  uncomment this volume mount.
      - ${GICKUP_KNOWN_HOSTS:-./known_hosts}:/root/.ssh/known_hosts
    command: ["/gickup/conf.yml"]
    environment:
      TZ: ${TZ:-Etc/UTC}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - gickup_net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_gickup
    restart: unless-stopped
    pull_policy: always
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the
      #  "com.centurylinklabs.watchtower.enable=true" label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gickup_net

```

And my backupss.yml gickup config:

## Crontab schedule to run gickup
cron: "*/15 * * * *"

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - user: "redjax"
      ssh: true
      ## Path in container
      key: "/root/.ssh/id_rsa"
      token_file: "/root/.ssh/github_token"
      ## Names of repositories to include
      include:
        - "dotfiles"
      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: true
      issues: true
      filter:
        # lastactivity: 1y
        excludearchived: true
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  gitea:
    - url: https://codeberg.org/
      user: redjax
      token_file: /root/.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: private
        organizations: private
      force: true
```

I had this issue with a past version of this configuration, where I was using the wrong parameters for my Github source:

```
## Crontab schedule to run gickup
cron: "*/15 * * * *"

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - url: "git@github.com:your-username"
      ssh: true
      ## Path in container
      key: "/root/.ssh/id_rsa"
      token_file: "/root/.ssh/github_token"
      ## Names of repositories to include
      include:
        - "repo1"
        - "repo2"
      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: true
      issues: true
      filter:
        # lastactivity: 1y
        excludearchived: true
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  gitea:
    - url: https://codeberg.org/
      user: your-username
      token_file: /root/.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: private
        organizations: private
      force: true

  ## Backup to an S3 bucket
  # s3:
  #   - endpoint: somewhere:9000
  #     structured: true
  #     bucket: bucket-name
  #     accesskey: your-access-key
  #     secretkey: your-secret-key
  #     usessl: true

  ## Backup to a Gitlab repository
  # gitlab:
  #   - token: some-token
  #     token_file: token.txt
  #     url: http(s)://url-to-gitlab
  #     force: true
  #     mirror:
  #       enabled: true

  ## Backup to Github repository
  # github:
  #   - token: some-token
  #     token_file: token.txt
  #     organization: myorg
  #     force: true
  #     visibility:
  #       repositories: private
```

I just double checked my dotfiles in the host mounted volume where gickup temporarily clones the repo, and it's a mix of my code and other random peoples' `dotfiles` repositories.

```
