### ISSUE TITLE
Gitlab CE "404 Not found" for Gickup >=0.10.32 when trying to download only personal repos

### ISSUE THREAD

**Issue by pertsevds** [cooperspencer/gickup#317]
Hello.

I have a problem with Gickup version >=0.10.32.

## What I'm trying to do

I'm backing up only my users personal repos from a private Gitlab CE server shared with other users. My personal username on this server is `myusername`.

## My Gickup config to download only personal repos

```
source:
  gitlab:
    - token: "TOKEN"
      url: https://my.repo.net
      wiki: false
      starred: false
      includeorgs:
        - myusername
destination:
  local:
    - path: /backup/
      bare: true
      structured: true
```

## What happens

With Gickup >=0.10.32 it prints error "ERR 404 Not Found stage=gitlab url=https://my.repo.net" and does not download anything.

## What is expected

Gickup downloads all my personal repos only.

## How it works with previous version

With Gickup 0.10.31 it works as expected. It downloads all my personal repos only.

**Comment by cooperspencer** [comment]
Hi,
I'll have a look. I'll get back to you as soon as I found something.

**Comment by cooperspencer** [comment]
You're right. The issue is that your user is not its own organization/group. Unfortunately, there's currently no way to clone only your personal repositories without also cloning those from groups you're a member of—which can be problematic for gitlab admins.

I'll add functionality to clone only the repositories owned by the user, but it will take me some time.

**Comment by pertsevds** [comment]
Thank you.

**Comment by rivolity** [comment]
Hello,
thanks for the grate tool <3
I think you can include the possibility to clone only groups, not all the organization groups.
like this

```
source:
  gitlab:
    - token: XXXXXXXX
      url: https://gitlab.com
      username: kubehat
      includegroups: # this includes only the following groups from the organizations
      #   - beherit
```
