### ISSUE TITLE
ERR [Name]: AlhaDashDot

### ISSUE THREAD

**Issue by redjax** [cooperspencer/gickup#319]
I have been running Gickup unattended for a while now (working great, thanks again for such a useful utility!). I recently checked on the logs and noticed this line in every one of the repositories the Gickup container is synchronizing:

```shell
gickup  | 2025-04-18 22:12:20 INF Read token file bytes=40 path=/root/.ssh/codeberg_token
gickup  | 2025-04-18 22:12:20 ERR [Name]: AlphaDashDot stage=gitea url=https://github.com/redjax/mygithub.git   <-------
gickup  | 2025-04-18 22:12:20 INF starting backup for https://github.com/redjax/neovim.git stage=backup
gickup  | 2025-04-18 22:12:20 INF opening neovim locally path=/backup/ stage=locally
gickup  | 2025-04-18 22:12:22 INF pulling neovim path=/backup/ stage=locally
gickup  | 2025-04-18 22:12:25 INF already up-to-date path=/backup/ stage=locally
gickup  | 2025-04-18 22:12:25 INF backing up issues path=/backup/ repo=neovim stage=locally
gickup  | 2025-04-18 22:12:25 INF pushing neovim to git-backup stage=s3 url=192.168.1.18:9000
gickup  | 2025-04-18 22:12:27 INF mirroring github.com/redjax/neovim to https://codeberg.org/ stage=gitea url=https://codeberg.org/
```

The 2nd line in the output above is the one I am here about, I'm not sure what it means, but I see this as the 2nd line in each repository Gickup synchs. It seems like the synchronization still completes without issue, but I'm curious what this message means and googling/searching around Github has not answered any questions.

Since this does not seem to be affecting synchronization, I don't think this is a bug or problem, just a curiosity :)

**Comment by cooperspencer** [comment]
That's weird. It comes from the gitea sdk I am using. https://github.com/go-gitea/gitea/issues/4827
Someone already complained about that cryptic error message. The repository you try to backup doesn't have a space in its name, does it?

**Comment by cooperspencer** [comment]
But I'll definitely have a look at that.

**Comment by redjax** [comment]
I do not have spaces in any of my repositories, but I noticed I had left an empty `- ""` in the `include:` section, I bet that was the cause... just waiting for it to synch now.

**Comment by redjax** [comment]
I removed the empty include, but I'm still getting the AlphaDashDot error.

Also, I'm noticing this happens on every `gitea` step for my codeberg.org repository. I see that things stopped synching successfully to codeberg as a result. In my original message I said it wasn't affecting synchronization, but it looks like it actually is affecting things.

**Comment by cooperspencer** [comment]
Could you share your configuration with me? I will try to fix that issue asap.

**Comment by cooperspencer** [comment]
Also which version of gickup are you using?

I just created a local forgejo instance and ran a backup for your user with the dev version and the latest release of gickup and that worked fine. Then I ran a backup to codeberg with just your `mygithub` repository and that worked well too.

**Comment by redjax** [comment]
I am running `gickup` in a Docker container. This is the configuration I'm using:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/cooperspencer/gickup/refs/heads/main/gickup_spec.json
## Crontab schedule to run gickup
cron: "*/15 * * * *"

log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - user: "redjax"
      ssh: true
      ## Path in container
      key: "/root/.ssh/id_rsa"
      token_file: "/root/.ssh/github_token"
      ## Names of repositories to include
      include:
        - "dotfiles"
        - "PowershellProfile"
        - "redkb"
        - "docker_templates"
        - "cookiecutter"
        - "weatherdata"
        - "red-utils"
        - "python_pkgs"
        - "MSLearn-AzureBicep"
        - "neovim"
        - "mygithub"
        - "starship"
        - "weathersched"
        - "uautils"
        - "Terraform"
        - "system_scripts"
        - "red-duck"
        - "pokepy"
        - "git-sync-repos"
        - "cflarepy"
        - "awesome-tools"
        - "Straind"
        - "auto-xkcd"
        - "SpacetradersProject"
        - "xkcd_data"
        - "pingpy"
        - "ansible_homelab"
        - "py-platform-info"
        - "ansible"
        - "cookiecutter-python-pdm"
        - "cookiecutter-python-uv"
        - "red-logging"
        - "PowershellModuleTemplate"
        - "vscode-devcontainers"
        - "bookmark-cleanup"
        - "transmissionpy"
        - "adventofcode"
        - "homelab_diagrams"
        - "nix-flakes"
        - "red-sysinfo"
        - "red-nox"
        - "git-mirror"
        - "semaphore-plays"
        - "transmission_scripts"
        - "PowershellModules"
        - "ntfy_scripts"
        - "ollama_scripts"
        - "crawlbookmarks"
        - "faker_utils"
        - "bluesky_scripts"
      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: false
      issues: true
      gists: true
      filter:
        # lastactivity: 1y
        excludearchived: false
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  gitea:
    - url: https://codeberg.org/
      user: redjax
      token_file: /root/.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: private
        organizations: private
      force: true

  ## Backup to an S3 bucket
  s3:
    - endpoint: <my-s3-ip>
      structured: true
      bucket: gickup-backups
      accesskey: <my-access-key>
      secretkey: <my-secret-key>
      usessl: false

  ## Backup to a Gitlab repository
  # gitlab:
  #   - token: some-token
  #     token_file: token.txt
  #     url: http(s)://url-to-gitlab
  #     force: true
  #     mirror:
  #       enabled: true

  ## Backup to Github repository
  # github:
  #   - token: some-token
  #     token_file: token.txt
  #     organization: myorg
  #     force: true
  #     visibility:
  #       repositories: private

```

And my `compose.yml`:

```yaml
---
networks:
  gickup_net: {}

volumes:
  gickup_logs: {}
  gickup_local_backups: {}

services:
  gickup:
    image: buddyspencer/gickup:${GICKUP_VERSION:-ubuntu-latest}
    container_name: gickup
    restart: unless-stopped
    volumes:
      - ${GICKUP_CONFIG:-./config/default.yml}:/gickup/conf.yml
      ## If using /backup/ in the container for local destination,
      #  mount it in a volume for persistence
      - ${GICKUP_BACKUP_DIR:-gickup_local_backups}:/backup
      ## Mount an SSH key, i.e. ~/.ssh/gickup_id_rsa
      #  Create a key with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/gickup_id_rsa -N ""
      - ${GICKUP_SSH_KEY}:/root/.ssh/id_rsa:ro
      ## Mount logging path to persist logs
      - ${GICKUP_LOGS_DIR:-gickup_logs}:/log
      ## Mount a Github PAT
      - ${GICKUP_GITHUB_PAT_FILE}:/root/.ssh/github_token:ro
      ## Mount a gitea/forgejo/codeberg PAT
      - ${GICKUP_CODEBERG_PAT_FILE}:/root/.ssh/codeberg_token:ro
      ## If you get errors about the container not being able to find a known_hosts file,
      #  create a file called 'known_hosts' in the same path as the compose.yml file and
      #  uncomment this volume mount.
      - ${GICKUP_KNOWN_HOSTS:-./known_hosts}:/root/.ssh/known_hosts
    command: ["/gickup/conf.yml"]
    environment:
      TZ: ${TZ:-Etc/UTC}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - gickup_net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_gickup
    restart: unless-stopped
    pull_policy: always
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the
      #  "com.centurylinklabs.watchtower.enable=true" label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gickup_net

```

**Comment by redjax** [comment]
I removed the S3 destination from my configuration as a test and noticed all repositories began synchronizing successfully again. I commented out this section:

```yaml
## Backup to an S3 bucket
  s3:
    - endpoint: <my-s3-ip>
      structured: true
      bucket: gickup-backups
      accesskey: <my-access-key>
      secretkey: <my-secret-key>
      usessl: false
```

In my setup, my endpoint is a local IP/port, i.e. `192.168.1.xxx:9000`.  I pased my `accesskey` and `secretkey`, in plain text, into the keys under `s3`. Should these be files like the Github/Codeberg PATs? I'm wondering if the problem is that `gickup` is expecting `accesskey` and `secretkey` to be filepaths that it loads the actual secret from, maybe?
