### ISSUE TITLE
Usage example for gitlab subgroups

### ISSUE THREAD

**Issue by h7x4** [cooperspencer/gickup#322]
Hello,

I've been trying to figure out how to make gickup pull repos from gitlab subgroups, but I don't seem to be able to get it working. Here's some of the things I've tried:

```yaml
# trying to clone https://gitlab.com/gitlab-org/api/client-go as an example
gitlab:
  - include:
    - client-go
    - api/client-go
    includeorgs:
    - gitlab-org
    - gitlab-org/api
    user: gitlab-org

  - include:
    - client-go
    - api/client-go
    includeorgs:
    - gitlab-org
    - gitlab-org/api
    user: gitlab-org/api

destination:
  local:
    - path: /home/h7x4/gickup
      structured: false
      zip: false
      keep: 5
      bare: false
```

<details>
  <summary>Output</summary>

```
$ gickup conf.yml --debug
2025-05-08T17:39:37+02:00 INF Reading conf.yml file=conf.yml
2025-05-08T17:39:37+02:00 INF Configuration loaded destinations=1 pairs=2 sources=2
2025-05-08T17:39:37+02:00 INF Backup run starting
2025-05-08T17:39:37+02:00 INF grabbing repositories from gitlab-org stage=gitlab url=https://gitlab.com
2025-05-08T17:39:44+02:00 INF grabbing repositories from gitlab-org/api stage=gitlab url=https://gitlab.com
2025-05-08T17:39:53+02:00 INF Backup run complete duration=16.122168626s
```

(no output files)

</details>

I see there is an attempt at adding subgroup support in https://github.com/cooperspencer/gickup/pull/261/files, and if I'm reading it right then gickup should just look for all of the subgroups automatically and go through them, meaning this should be correct?

```yaml
  gitlab:
  - include:
    - client-go
    includeorgs:
    - gitlab-org
    user: gitlab-org
```

Not sure if I'm doing something wrong, or if this is a bug. Either way, it would probably be good to have an example of subgroup usage in the example config.

**Comment by cooperspencer** [comment]
Hi,

that is a bug. I only list groups that the user who created a token is in and if there is no token, groups are ignored.
I have to fix that.

in the meantime you could do this:
```yaml
source:
  any: 
    - url: https://gitlab.com/gitlab-org/api/client-go
```
