### ISSUE TITLE
Mirroring torvalds/linux takes a lot of cpu and memory

### ISSUE THREAD

**Issue by mio-19** [cooperspencer/gickup#333]
This program took 5G of memory and a lot of cpu when mirroring https://github.com/torvalds/linux to my gitea instance

My configuration looks like this

```yaml
source:
  github:
    <more repo>
    - user: torvalds
      token: <token>
      include: 
        - linux
      wiki: true
      issues: true
destination:
  gitea:
    - token: <token>
      url: <url>
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: public
        organizations: public
      force: false
```
