### ISSUE TITLE
WRN can't fetch issues

### ISSUE THREAD

**Issue by mio-19** [cooperspencer/gickup#334]
I am running gickup with docker compose;

```

runner-1  | 2025-06-28T00:23:28Z INF grabbing the repositories from luanti-org stage=github url=https://github.com
runner-1  | 2025-06-28T00:25:08Z WRN can't fetch issues error="GET https://api.github.com/repos/luanti-org/luanti/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=luanti stage=github url=https://github.com
runner-1  | 2025-06-28T00:25:13Z WRN can't fetch issues error="GET https://api.github.com/repos/luanti-org/luanti/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=luanti stage=github url=https://github.com
runner-1  | 2025-06-28T00:25:19Z WRN can't fetch issues error="GET https://api.github.com/repos/luanti-org/luanti/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=luanti stage=github url=https://github.com
runner-1  | 2025-06-28T00:25:24Z WRN can't fetch issues error="GET https://api.github.com/repos/luanti-org/luanti/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=luanti stage=github url=https://github.com
runner-1  | 2025-06-28T00:25:29Z WRN can't fetch issues error="GET https://api.github.com/repos/luanti-org/luanti/issues?page=100&per_page=100&state=all: 422 Pagination with the page parameter is not supported for large datasets, please use cursor based pagination (after/before) []" repo=luanti stage=github url=https://github.com
```

My config looks like this:

```yaml
source:
  github:
    <other repos>
    - user: luanti-org
      token: <token>
      include: 
        - luanti
      wiki: true
      issues: true
destination:
  gitea:
    - token: <token>
      url: <url>
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: public
        organizations: public
      force: false
```

docker-compose.yml

```yaml

services:
  runner:
    restart: unless-stopped
    # build: . # If you want to Build the Image locally (You need the complete Repo on your PC)
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml # Change the path of your local config ${PWD} is your current directory (where the docker-compose.yml is located)
    command: ["/gickup/conf.yml"] # Changes the path of the internal bound config
    # Uncomment these 2 lines and set timezone appropriately to specify cron in local time instead of UTC.
    # environment:
    #   - TZ=America/Los_Angeles

```
