### ISSUE TITLE
could not find repo on sourcehut

### ISSUE THREAD

**Issue by mio-19** [cooperspencer/gickup#335]
```
runner-1  | 2025-06-28T02:07:49Z INF grabbing repositories from vdupras stage=sourcehut url=https://git.sr.ht/
runner-1  | 2025-06-28T02:07:51Z ERR couldn't find any repositories for user ~vdupras stage=sourcehut url=https://git.sr.ht/

```

my config

```
source:
  sourcehut:
    - user: vdupras
      username: ...
      password: ...
      include:
        - duskos
      wiki: true
      issues: true
destination:
  gitea:
    - token: <token>
      url: <url>
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: public
        organizations: public
      force: false
```
