### ISSUE TITLE
Automatically include repositories from github orgas

### ISSUE THREAD

**Issue by pschichtel** [cooperspencer/gickup#43]
I'm not sure this is supposed to work, but for me it doesn't include the repositories from my github orgas.

**Comment by cooperspencer** [comment]
that should work, there is just a little trick to do in the config.
when I add my user to the config, the api looks up my user and I get back just my public repos.
```yaml
source:
  github:
    - token: <redacted>
      user: cooperspencer
```

```bash
ls | wc -l
41
```

if I only have the token, the api looks up the api user and I get all of the repositories of this user.
```yaml
source:
  github:
    - token: <redacted>
```

```bash
ls | wc -l
48
```

The module I am using for github is handling that a little bit weird.
https://pkg.go.dev/github.com/google/go-github/v41/github#RepositoriesService.List
