### ISSUE TITLE
Issue installing via Docker Synology package

### ISSUE THREAD

**Issue by searls** [cooperspencer/gickup#58]
Forgive me, as I'm a complete Docker noob and am probably missing something. Any advice or guidance here would be very welcome! 🙏 

When I install and set up the image using Synology docker (pulling either the `latest` or `main` tags from docker hub):

<img width="1006" alt="Screen Shot 2021-12-21 at 11 17 23" src="https://user-images.githubusercontent.com/79303/146963241-41504364-36f9-464f-8318-c023eb38e330.png">

With `/gickup/code` being the local directory I've configured to clone my repos to:

<img width="1015" alt="Screen Shot 2021-12-21 at 11 18 04" src="https://user-images.githubusercontent.com/79303/146963258-94d019f2-f31d-4a5a-bd17-38e244f1f19d.png">

 I get errors that `conf.yml` is missing, as if it's trying to run a build:

<img width="894" alt="Screen Shot 2021-12-21 at 11 15 26" src="https://user-images.githubusercontent.com/79303/146963078-224ae237-0e7d-44f9-98c0-0a69e080a2db.png">

I tried adding an empty `conf.yml` (I don't know what needs to go into one) and the container still stops in error, but no longer logs anything.

**Comment by cooperspencer** [comment]
No worries 😁
You need to add your 'conf.yml' to '/', maybe your 'code' directory too.

**Comment by searls** [comment]
Yeah, that's what I did earlier, but an empty `conf.yml` (I don't know what should go in one, as I don't know any golang conventions) resulted in the service still stopping unexpectedly (this time with no error logged)

**Comment by cooperspencer** [comment]
it probably looks something like this for you.
```yaml
source:
  github:
    - token: some-token # if you have any private repos, add a token
      user: searls

destination:
  local:
    - path: /gickup/code
      structured: true

cron: 0 22 * * *
```
when gickup runs, it tries to open the default config file, which is `conf.yml`, in your current directory.
so just add your configuration to `/conf.yml` and you should be fine.
