### ISSUE TITLE
Gitlab Back Up User and Group

### ISSUE THREAD

**Issue by pew** [cooperspencer/gickup#61]
I've got a Group and User in GitLab, gickup only picks up the Group- and not the user repositories. I'm not sure if that is related to #40

**Comment by cooperspencer** [comment]
Are you on the latest version? Can you share your config file?

**Comment by pew** [comment]
I'm on the latest Docker release: v0.9.8-2, here's the config file:

```
source:
  gitlab:
    - token: abcdef1234
      ssh: false

destination:
  local:
    - path: /backup
      structured: true
```
