### ISSUE TITLE
Gitea source 403 Forbidden Error

### ISSUE THREAD

**Issue by Zelec** [cooperspencer/gickup#65]
I have a gitea server setup at https://git.tgdev.ca

When I set it up as a gickup source I always get `FTL 403 Forbidden stage=gitea url=https://git.tgdev.ca`
Error occurs on both the docker image and running the direct go release
User + Password, Token only, or just SSH, all report 403

Yet I can go to https://git.tgdev.ca/api/swagger and use the token no problem

Here is the log file that is generated
```
{"level":"info","stage":"gitea","url":"https://git.tgdev.ca","time":"2021-12-22T14:41:46-05:00","message":"grabbing repositories from Zelec"}
{"level":"fatal","stage":"gitea","url":"https://git.tgdev.ca","time":"2021-12-22T14:41:46-05:00","message":"403 Forbidden"}
```

And here is the config file for reference
```yaml
source:
  gitea:
    - token: REDACTED
      user: Zelec
      url: https://git.tgdev.ca
      ssh: true
      sshkey: /gickup/ssh/id_rsa

destination:
  local:
    - path: /gickup/data
      structured: true
```

Am I missing anything obvious?
