### ISSUE TITLE
minor documentation info

### ISSUE THREAD

**Issue by vinceskahan** [cooperspencer/gickup#70]
Just a note re: docker documentation.  It's a little confusing figuring out what to do to run the container and save the output locally so I took a couple minutes to write up a couple items that might help if you ever do a FAQ or wiki.

Some things I noted running the docker image:

### Cron ###
- if cron is enabled, it will run at that time (seemingly UTC) and stay running
- if cron is not enabled, it will run once and exit

### Saving output locally ###

To save local output, define it in config.yml ala:
```
destination:
     local:
       - path: /output
```
and add a corresponding volumes entry to map that to a path on your host os

```
version: "3"
services:
  runner:
    # build: . # If you want to Build the Image locally (You need the complete Repo on your PC)
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml
      - /my/local/path/to/write/to:/output
    command: ["./gickup/app", "/gickup/conf.yml"]
```
