### ISSUE TITLE
[Question] - Backup multiple users from same host

### ISSUE THREAD

**Issue by vic1707** [cooperspencer/gickup#84]
I'm wondering if there is a configuration setting to backup multiple users from the same host?
Can I simply put in my config
```yml
source:
  github:
    -  user: user1
        token: ...
  github:
    -  user: user2
        token: ...
```
or should I run two instances of gickup? 🤔

**Comment by cooperspencer** [comment]
No need for two instances. That should do it:
```yaml
source:
  github:
    -  user: user1
        token: ...
    -  user: user2
        token: ...
```
