### ISSUE TITLE
Gitlab does not respect include/exclude settings

### ISSUE THREAD

**Issue by drewmoseley** [cooperspencer/gickup#90]
I've been unable to get my gitlab config to respect any of the include/exclude settings I throw at it. I have one or two repos that I no longer have access to, even though they show in my list of contributions, and I have been unable to figure out what syntax to use to exclude them. I have tried explicit includeorgs as well as excludeorgs and exclude settings all with no luck.

Has anyone successfully used those setting with gitlab?

**Comment by cooperspencer** [comment]
I just tried those settings in my config-file and they work fine:
```yaml
source:
  gitlab:
   - user: buddyspencer
     token: <redacted>
     include:
        - phorge
destination:
  local:
    - path: ~/backup
      structured: true
```
```yaml
source:
  gitlab:
   - user: buddyspencer
     token: <redacted>
     exclude:
        - phorge
destination:
  local:
    - path: ~/backup
      structured: true
```
